# Made by Agazed.
# Visit me @ agazed.net!

# How many help messages do you want on one page?
messages-per-page: 8

# Do you want to display the top header message?
display-header: true

#Shall the header be displayed on the last page?
show-header-on-last-page: true

# Top header message. Available variables: %NEXTPAGE, %CURRENTPAGE, %TOTALPAGES.
header: '&7Page: %CURRENTPAGE/%TOTALPAGES'

# Do you want to display the bottom footer message?
display-footer: true

#Shall the footer be displayed on the last page?
show-footer-on-last-page: false

# Bottom footer message. Available variables: %NEXTPAGE, %CURRENTPAGE, %TOTALPAGES.
footer: '&7Type /help %NEXTPAGE to get to the next page'

# ---------- Your custom help messages ----------

# This is the default list. People who have access to this list either have multiple list permissions, no list permissions, or the permission for the list they have is empty.
default:
- 'A message'
- 'Another message'
- '&2Colored message!'
- 'The list goes on...'

# Example: To grant access to this list, grant the permission "help.list.test".
test:
- 'Test list'

# Another example. Again, to assign this list to people, simply give them the "help.list.foobar" permission. You can name a list anything you want.
foobar:
- 'Foobar!'
