name: CustomHelpPages
author: Agazed
description: Auto modulating custom help pages
website: http://agazed.net
main: net.agazed.help.Help
version: 2.0
commands:
  help:
    description: Main command
permissions:
  help.help:
    description: Main permission
    default: true
  help.view:
    description: View other pages
    default: op
  help.reload:
    description: Reload permission
    default: op
